apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: dilankarathnasiri/simple-web-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "8000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-app-http-route
  namespace: app
spec:
  parentRefs:
    - name: envoy-gateway
  rules:
    - matches:
        - path:
            type: Exact
            value: "/web-app-svc"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: "/"
      backendRefs:
        - name: web-app-svc
          port: 80
