apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-2
  template:
    metadata:
      labels:
        app: microservice-2
    spec:
      containers:
        - name: microservice-2
          image: dilankarathnasiri/spring-k8s:microservice-2
          ports:
            - containerPort: 5001
